// Users
export const GET_POSTS_SUCCSESS= 'GET_POSTS_SUCCSESS';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const GET_POST_BY_ID = 'GET_POST_BY_ID';
export const CREATE_POST = 'CREATE_POST';
export const EDIT_POST = 'EDIT_POST';

export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS'
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const GET_CATEGORY_BY_ID = 'GET_CATEGORY_BY_ID';
export const CREATE_CATEGORY= 'CREATE_CATEGORY';
export const EDIT_CATEGORY = 'EDIT_CATEGORY';

export const GET_ALL_FILES = 'GET_ALL_FILES'
export const UPLOAD_FILE = 'UPLOAD_FILE'